### ISSUE TITLE
initial design notes

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/pfe-lab#122]
place for initial design notes...

**Comment by beckyrother** [comment]
Went through page-by-page and have some more comments:
## Edit
![org-edit](https://user-images.githubusercontent.com/1392130/31194358-88c45c44-a90c-11e7-9d66-9db0398be10d.png)
- [ ]  every text input label should be the same style as "Name"
- [ ]  text everywhere is kind of small – check the Project Builder for good sizes
- [ ]  the Delete button is too big. Can it be the same style as in the build a project section?
- [ ]  add more space (30px) above divider lines
- [ ]  make space under text input labels consistent (15px)

## About
- [ ]  use the same text input label style as "Name" from Edit
- [ ]  please add the text about what this page is above the "create page" button, so users know what it is they're creating
- [ ]  "Create a new about page" button style - can it be like the "Add user role" button from the build project section? 
![edit button](https://user-images.githubusercontent.com/1392130/31194537-12da8b92-a90d-11e7-9b75-e1075ccf1773.png)

## Collaborators
- [ ]  will there be other roles in the future? otherwise just say "Add another collaborator" rather than "Add another user role"

## Projects
- [ ]  Add the ability to create a project from this section
- [ ]  Add a separate section for "unknown" projects
