### ISSUE TITLE
Staging deploy uses production client ID for auth

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/pfe-lab#199]
Staging deploy uses production client ID for auth instead of staging client ID. I've updated production Doorkeeper so staging deploy allows sign-in (to production, not what desired which would be to staging API) until resolved.

**Comment by mcbouslog** [comment]
Looked into this a little, still can't figure out why `npm stage` results in `config.js` with an `envFromShell = production`. Console logged `process.env.NODE_ENV` from webpack.production.config.js and it's `staging` as would expect, but somewhere between `webpack.production.config.js` and `config.js` it's changing from `staging` to `production`.

**Comment by srallen** [comment]
I'm guessing the `mode: 'production'` in the production config is taking precedence and is setting the environment to production despite the environment plugin a few lines below, so if the staging deploy script is using this, then it will deploy using the production environment? I think we have a similar problem with zooniverse classroom's webpack setup, likely borrowed from each other since they were developed around the same time.

**Comment by srallen** [comment]
Maybe a separate staging config needs to be defined? Seems like this should work though. Perhaps later webpack versions broke this kind of setup.

**Comment by mcbouslog** [comment]
Noting https://github.com/zooniverse/edu-api-front-end/pull/174 is indeed same issue.
